version: "3"

services:
    app: # 서비스 이름
        build:
            context: app  #app 폴더에서 찾는다.
        ports:
            - "5000" #5000번 포트를 사용한다고 명시
    
    nginx:
        image: nginx:latest #base 이미지 설치
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro #참조할 파일 설정
        depends_on:
            - app #app 서비스가 실행된 이후에 실행된다.
        ports:
            - "80:80" #80번 포트를 80번 포트에 맵핑 시켜준다.
